function createDatacenterWithEnclosure(NameValueArgs)
% Build datacenter of desired fidelity and rating in a rectangular room.
% 
% For more details, see <a href="matlab:web('FunctionReferenceList.html')">Function Reference List</a>
% 
% Copyright 2025 - 2026 The MathWorks, Inc.

    arguments(Input)
        NameValueArgs.NumPDUunitsX (1,1) {mustBeGreaterThan(NameValueArgs.NumPDUunitsX,1)}
        NameValueArgs.NumPDUunitsY (1,1) {mustBeGreaterThan(NameValueArgs.NumPDUunitsY,1)}
        NameValueArgs.ModelName string {mustBeText}
        NameValueArgs.ModelOption string {mustBeMember(NameValueArgs.ModelOption,["Thermal","Electrothermal"])}
        NameValueArgs.RatingDatacenter (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.RatingDatacenter, "kW")} = simscape.Value(50, "kW")
        NameValueArgs.PowerSupplyEff (1,1) {mustBeBetween(NameValueArgs.PowerSupplyEff,0,100)} = 85
        NameValueArgs.ThermalRes (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.ThermalRes, "K/W")} = simscape.Value(1, "K/W")
        NameValueArgs.EnclosureName string {mustBeText} = "Room"
        NameValueArgs.RoomLength (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.RoomLength, "m")}
        NameValueArgs.RoomWidth (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.RoomWidth, "m")}
        NameValueArgs.RoomHeight (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.RoomHeight, "m")}
        NameValueArgs.WallThickness (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.WallThickness, "m")}
        NameValueArgs.RoomRotate (1,1) simscape.Value {simscape.mustBeCommensurateUnit(NameValueArgs.RoomRotate, "deg")}
        NameValueArgs.PercentAirVolInRoom (1,1) {mustBeBetween(NameValueArgs.PercentAirVolInRoom,0,100)} = 10
        NameValueArgs.Diagnostics logical {mustBeNumericOrLogical} = false
    end
    % Open Model.
    open_system(new_system(NameValueArgs.ModelName));
    % Add datacenter of Thermal option to the model.
    datacenter = buildDatacenter(NumPDUunitsX=NameValueArgs.NumPDUunitsX,...
                                 NumPDUunitsY=NameValueArgs.NumPDUunitsY,...
                                 ModelName=NameValueArgs.ModelName,...
                                 ModelOption=NameValueArgs.ModelOption,...
                                 RatingDatacenter=NameValueArgs.RatingDatacenter,...
                                 PowerSupplyEff=NameValueArgs.PowerSupplyEff,...
                                 ThermalRes=NameValueArgs.ThermalRes,...
                                 Diagnostics=NameValueArgs.Diagnostics);
    % Add room to around the datacenter unit.
    roomModel = buildEnclosureForDatacenter(ModelName=NameValueArgs.ModelName,...
                                            DatacenterModel=datacenter,...
                                            EnclosureName=NameValueArgs.EnclosureName,...
                                            PercentAirVolInRoom=8,...
                                            RoomLength=NameValueArgs.RoomLength,...
                                            RoomWidth=NameValueArgs.RoomWidth,...
                                            RoomHeight=NameValueArgs.RoomHeight,...
                                            WallThickness=NameValueArgs.WallThickness,...
                                            RoomRotate=NameValueArgs.RoomRotate,...
                                            Diagnostics=NameValueArgs.Diagnostics);
    % Save and close datacenter custom library
    projRootDir = currentProject().RootFolder;
    saveFileLoc = fullfile(projRootDir,"Workflow","DatacenterUtilizationAnalysis",NameValueArgs.ModelName);
    save_system(NameValueArgs.ModelName,saveFileLoc);
    close_system(NameValueArgs.ModelName);
    save(saveFileLoc,'datacenter','roomModel');
    if NameValueArgs.Diagnostics, disp(strcat("Build completed. To get started, open the model file '",...
            saveFileLoc,"' and copy the subsystem 'Datacenter' and '",NameValueArgs.EnclosureName,...
            "' on to your model canvas.")); 
    end
end